// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	DbUser
	ApiUser
*/
package example

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/zanven42/proto-database-go/dbproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// sqlx
// dbName1
// dbName2
// db table
// Database and Table definitions
var db string = "db"
var db_table string = "table"

// var: Hello - DBName: _hello
// var: Apiuser.ID - DBName: _Id
