// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: database.proto

/*
Package dbproto is a generated protocol buffer package.

It is generated from these files:
	database.proto

It has these top-level messages:
*/
package dbproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

var E_Sqlxdb = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64100,
	Name:          "dbproto.sqlxdb",
	Tag:           "varint,64100,opt,name=sqlxdb",
	Filename:      "database.proto",
}

var E_Dbname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64101,
	Name:          "dbproto.dbname",
	Tag:           "bytes,64101,opt,name=dbname",
	Filename:      "database.proto",
}

var E_Tablename = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64102,
	Name:          "dbproto.tablename",
	Tag:           "bytes,64102,opt,name=tablename",
	Filename:      "database.proto",
}

var E_Query = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64103,
	Name:          "dbproto.query",
	Tag:           "bytes,64103,opt,name=query",
	Filename:      "database.proto",
}

var E_Colname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65100,
	Name:          "dbproto.colname",
	Tag:           "bytes,65100,opt,name=colname",
	Filename:      "database.proto",
}

var E_Key = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65101,
	Name:          "dbproto.key",
	Tag:           "varint,65101,opt,name=key",
	Filename:      "database.proto",
}

var E_Autokey = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65102,
	Name:          "dbproto.autokey",
	Tag:           "varint,65102,opt,name=autokey",
	Filename:      "database.proto",
}

var E_Filterequal = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65103,
	Name:          "dbproto.filterequal",
	Tag:           "varint,65103,opt,name=filterequal",
	Filename:      "database.proto",
}

var E_Filtergreaterthan = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65104,
	Name:          "dbproto.filtergreaterthan",
	Tag:           "varint,65104,opt,name=filtergreaterthan",
	Filename:      "database.proto",
}

var E_Filterlessthan = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65105,
	Name:          "dbproto.filterlessthan",
	Tag:           "varint,65105,opt,name=filterlessthan",
	Filename:      "database.proto",
}

var E_Filterwildcardboth = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65106,
	Name:          "dbproto.filterwildcardboth",
	Tag:           "varint,65106,opt,name=filterwildcardboth",
	Filename:      "database.proto",
}

var E_Filterwildcardfront = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65107,
	Name:          "dbproto.filterwildcardfront",
	Tag:           "varint,65107,opt,name=filterwildcardfront",
	Filename:      "database.proto",
}

var E_Filterwildcardback = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65108,
	Name:          "dbproto.filterwildcardback",
	Tag:           "varint,65108,opt,name=filterwildcardback",
	Filename:      "database.proto",
}

var E_Filterall = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65109,
	Name:          "dbproto.filterall",
	Tag:           "varint,65109,opt,name=filterall",
	Filename:      "database.proto",
}

var E_Filterdefault = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65110,
	Name:          "dbproto.filterdefault",
	Tag:           "varint,65110,opt,name=filterdefault",
	Filename:      "database.proto",
}

var E_Queryfilter = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65111,
	Name:          "dbproto.queryfilter",
	Tag:           "varint,65111,opt,name=queryfilter",
	Filename:      "database.proto",
}

func init() {
	proto.RegisterExtension(E_Sqlxdb)
	proto.RegisterExtension(E_Dbname)
	proto.RegisterExtension(E_Tablename)
	proto.RegisterExtension(E_Query)
	proto.RegisterExtension(E_Colname)
	proto.RegisterExtension(E_Key)
	proto.RegisterExtension(E_Autokey)
	proto.RegisterExtension(E_Filterequal)
	proto.RegisterExtension(E_Filtergreaterthan)
	proto.RegisterExtension(E_Filterlessthan)
	proto.RegisterExtension(E_Filterwildcardboth)
	proto.RegisterExtension(E_Filterwildcardfront)
	proto.RegisterExtension(E_Filterwildcardback)
	proto.RegisterExtension(E_Filterall)
	proto.RegisterExtension(E_Filterdefault)
	proto.RegisterExtension(E_Queryfilter)
}

func init() { proto.RegisterFile("database.proto", fileDescriptorDatabase) }

var fileDescriptorDatabase = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd4, 0x4d, 0x4f, 0x22, 0x31,
	0x18, 0x07, 0xf0, 0x6c, 0xc8, 0x2e, 0x3b, 0xdd, 0x2c, 0x89, 0x78, 0x31, 0x26, 0x46, 0x8e, 0x9e,
	0x86, 0x78, 0x32, 0x34, 0x31, 0x46, 0x13, 0xf5, 0x44, 0x88, 0x1c, 0xbd, 0x3d, 0x33, 0x7d, 0x66,
	0x98, 0x50, 0xa7, 0xd0, 0x76, 0xa2, 0x7c, 0x47, 0xdf, 0x5f, 0xbf, 0x80, 0x2f, 0x5f, 0xc0, 0x23,
	0x07, 0x33, 0xd3, 0x4e, 0x00, 0xc1, 0x94, 0x1b, 0x7d, 0xf2, 0xff, 0xfd, 0x5b, 0xa0, 0x33, 0xa4,
	0xc6, 0x40, 0x43, 0x00, 0x0a, 0xfd, 0x81, 0x14, 0x5a, 0xd4, 0xab, 0x2c, 0x28, 0x3e, 0xac, 0x37,
	0x62, 0x21, 0x62, 0x8e, 0xcd, 0x62, 0x15, 0x64, 0x51, 0x93, 0xa1, 0x0a, 0x65, 0x32, 0xd0, 0x42,
	0x9a, 0x28, 0x6d, 0x91, 0x3f, 0x6a, 0xc8, 0x2f, 0x58, 0x50, 0xdf, 0xf4, 0x4d, 0xd8, 0x2f, 0xc3,
	0x7e, 0x1b, 0x95, 0x82, 0x18, 0x3b, 0x03, 0x9d, 0x88, 0x54, 0xad, 0xbd, 0x7e, 0x56, 0x1a, 0xbf,
	0xb6, 0xfe, 0x76, 0x2d, 0xc8, 0x29, 0x0b, 0x52, 0x38, 0x43, 0x37, 0x7d, 0x2b, 0xa8, 0xd7, 0xb5,
	0x80, 0xee, 0x11, 0x4f, 0x43, 0xc0, 0x71, 0x39, 0xfd, 0x6e, 0xf5, 0xc4, 0xd0, 0x1d, 0xf2, 0x7b,
	0x98, 0xa1, 0x1c, 0xb9, 0xf1, 0x87, 0xc5, 0x26, 0x4f, 0x5b, 0xa4, 0x1a, 0x0a, 0x5e, 0xec, 0xbb,
	0x31, 0x47, 0x8f, 0x12, 0xe4, 0xac, 0x84, 0x97, 0x63, 0x03, 0xcb, 0x3c, 0xdd, 0x26, 0x95, 0x3e,
	0x8e, 0x5c, 0xec, 0x6a, 0x6c, 0x7e, 0xa5, 0x3c, 0x9b, 0xef, 0x06, 0x99, 0x16, 0x4b, 0xb0, 0x6b,
	0xcb, 0xca, 0x3c, 0xdd, 0x27, 0xff, 0xa2, 0x84, 0x6b, 0x94, 0x38, 0xcc, 0x80, 0xbb, 0xf8, 0x8d,
	0xe5, 0xd3, 0x86, 0xb6, 0xc9, 0x8a, 0x59, 0xc6, 0x12, 0x41, 0xa3, 0xd4, 0x3d, 0x48, 0x5d, 0x45,
	0xb7, 0xb6, 0x68, 0x5e, 0xd2, 0x63, 0x52, 0x33, 0x43, 0x8e, 0x4a, 0x2d, 0xd3, 0x75, 0x67, 0xbb,
	0xbe, 0x31, 0xda, 0x21, 0x75, 0x33, 0x39, 0x4f, 0x38, 0x0b, 0x41, 0xb2, 0x40, 0xe8, 0x9e, 0xab,
	0xec, 0xde, 0x96, 0x2d, 0xa0, 0xf4, 0x84, 0xac, 0xce, 0x4e, 0x23, 0x29, 0x52, 0xed, 0x6a, 0x7c,
	0xb0, 0x8d, 0x8b, 0xec, 0x82, 0x33, 0x42, 0xd8, 0x77, 0x35, 0x3e, 0xfe, 0x70, 0x46, 0x08, 0xfb,
	0x74, 0x97, 0x78, 0x66, 0x0a, 0xdc, 0xf9, 0x6f, 0x3e, 0xd9, 0x9e, 0x89, 0xa0, 0x87, 0xe4, 0xbf,
	0x59, 0x30, 0x8c, 0x20, 0xe3, 0xce, 0x2f, 0xf7, 0x6c, 0x2b, 0x66, 0x55, 0x7e, 0xab, 0x8a, 0xe7,
	0xc0, 0x4c, 0x5d, 0x25, 0x2f, 0xe5, 0xad, 0x9a, 0x32, 0x07, 0xde, 0x69, 0xf9, 0x7a, 0xf9, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x76, 0x7f, 0x57, 0x5a, 0x78, 0x04, 0x00, 0x00,
}
